CREATE TABLE [dbo].[OrderContent]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [OrderId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [Order] (Id),
  [VehicleId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Vehicle (Id),
  [VehicleUsDollarRatePerDay] DECIMAL (8,2) NOT NULL,
  [DateFrom] DATETIME NOT NULL,
  [DateTo] DATETIME NOT NULL
)
