CREATE TABLE [dbo].[Vehicle]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  [TypeId] INT NOT NULL,
  [MakeId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES VehicleMake(Id),
  [Name] VARCHAR(255) NOT NULL,
  [UsDollarRatePerDay] DECIMAL(8,2) NOT NULL,
  [NumberAvailable] INT NOT NULL
)
